artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://zissou.infosci.cornell.edu/convokit/datasets/movie-corpus/movie-corpus.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_format:
  datafile: artifacts/data_ingestion/movie-corpus/formatted_movie_lines.txt
  utterances: artifacts/data_ingestion/movie-corpus/utterances.jsonl

data_load:
  save_dir: artifacts/save
  corpus_name: movie-corpus
  corpus: artifacts/movie-corpus
  datafile: artifacts/data_ingestion/movie-corpus/formatted_movie_lines.txt

training:
  save_dir: artifacts/save
  model_name: cb_model
  corpus_name: movie-corpus
  # Set checkpoint to load from; set to None if starting from scratch
  loadFilename: