artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://zissou.infosci.cornell.edu/convokit/datasets/movie-corpus/movie-corpus.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_format:
  datafile: artifacts/data_ingestion/movie-corpus/formatted_movie_lines.txt
  utterances: artifacts/data_ingestion/movie-corpus/utterances.jsonl